# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' This is a simple function using Rcpp that performs Euclides algorithm
#' @param a numeric
#' @param b numeric
#' @export
gcd <- function(a, b) {
    .Call(`_helloRcpp_gcd`, a, b)
}

rcpp_hello <- function() {
    .Call(`_helloRcpp_rcpp_hello`)
}

